### ISSUE TITLE
How to use quicktype programtically?

### ISSUE THREAD

**Issue by Acrontum-Carmichael** [quicktype/quicktype#1357]
This command works as perfectly:
```
node ./node_modules/quicktype/dist/cli/index.js --just-types --src Weather.json --src-lang schema --acronym-style original --lang ts
```

I cannot see the docs on how to achieve the same via script, even passing the args to the index.js main function does not work:
```
const quicktype = require('quicktype');
    return await quicktype.main([
      '--just-types',
      '--src',
      'Weather.json',
      '--src-lang',
      'schema',
      '--acronym-style',
      'original',
      '--lang',
      'ts',
    ]);
``` 
It outputs an error:
```
src/lib/generate/generateTypeScriptInterfaceText.ts:38
    QuickTypeError: Internal error: Defined value expected, but got undefined
        at Object.messageError (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Messages.js:92:11)
        at panic (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/support/Support.js:69:23)
        at Object.defined (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/support/Support.js:49:12)
        at Ref.get address [as address] (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/input/JSONSchemaInput.js:136:26)
        at Resolver.<anonymous> (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/input/JSONSchemaInput.js:502:54)
        at Generator.next (<anonymous>)
        at fulfilled (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/input/JSONSchemaInput.js:4:58) {
      errorMessage: 'Internal error: ${message}',
      messageName: 'InternalError',
      properties: { message: 'Defined value expected, but got undefined' }
    }

```

**Comment by dvdsgl** [comment]
Here is the function definition: https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/Run.ts#L637

It takes a `Partial<Options>` as its only argument, not a `string[]`.

**Comment by Acrontum-Carmichael** [comment]
Yes I tried this too but it did not work @dvdsgl 

These options work via command line:
```
    return await commandRun('node', [
      path.join('./node_modules/quicktype/dist/cli/index.js'),
      '--just-types',
      '--src',
      'filepath.json',
      '--src-lang',
      'schema',
      '--acronym-style',
      'original',
      '--top-level',
      'someName',
      '--lang',
      'ts',
    ]);
```

Digging through the types my best guess was:
```
    return quicktype({
      inputData: definitionObject,
      lang: 'ts',
      noRender: true,
      rendererOptions: {
        'justTypes': 'true',
        'acronymStyle': 'original',
        'topLevel': mainInterfaceName
      }
    });
```

But this errors:
```
TypeError: allInputs.addTypes is not a function
        at Run.<anonymous> (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:193:40)
        at Generator.next (<anonymous>)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:7:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:3:12)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:192:53
        at Run.<anonymous> (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:165:34)
        at Generator.next (<anonymous>)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:7:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:3:12)
        at Run.timeSync (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:163:16)
        at Run.<anonymous> (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:192:24)
        at Generator.next (<anonymous>)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:7:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:3:12)
        at Run.makeGraph (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:190:16)
        at Run.<anonymous> (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:309:38)
        at Generator.next (<anonymous>)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:7:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:3:12)
        at Run.run (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:303:16)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:337:39
        at Generator.next (<anonymous>)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:7:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:3:12)
        at quicktypeMultiFile (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:336:12)
        at Object.<anonymous> (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:384:30)
        at Generator.next (<anonymous>)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:7:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:3:12)
        at Object.quicktype (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/quicktype/dist/quicktype-core/Run.js:383:12)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/src/lib/generate/generateTypeScriptInterfaceText.ts:23:12
        at step (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:136:27)
        at Object.next (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:117:57)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:110:75
        at new Promise (<anonymous>)
        at Object.__awaiter (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:106:16)
        at Object.default (/home/carmichael/code/open-source-projects/openapi-nodegen/src/lib/generate/generateTypeScriptInterfaceText.ts:7:90)
        at OpenAPIBundler.<anonymous> (/home/carmichael/code/open-source-projects/openapi-nodegen/src/lib/openapi/OpenAPIBundler.ts:212:57)
        at step (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:136:27)
        at Object.next (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:117:57)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:110:75
        at new Promise (<anonymous>)
        at Object.__awaiter (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:106:16)
        at OpenAPIBundler.Object.<anonymous>.OpenAPIBundler.injectDefinitionInterfaces (/home/carmichael/code/open-source-projects/openapi-nodegen/src/lib/openapi/OpenAPIBundler.ts:245:24)
        at OpenAPIBundler.<anonymous> (/home/carmichael/code/open-source-projects/openapi-nodegen/src/lib/openapi/OpenAPIBundler.ts:164:28)
        at step (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:136:27)
        at Object.next (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:117:57)
        at /home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:110:75
        at new Promise (<anonymous>)
        at Object.__awaiter (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:106:16)
        at OpenAPIBundler.Object.<anonymous>.OpenAPIBundler.injectInterfaces (/home/carmichael/code/open-source-projects/openapi-nodegen/src/lib/openapi/OpenAPIBundler.ts:181:24)
        at OpenAPIBundler.<anonymous> (/home/carmichael/code/open-source-projects/openapi-nodegen/src/lib/openapi/OpenAPIBundler.ts:93:28)
        at step (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:136:27)
        at Object.next (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:117:57)
        at fulfilled (/home/carmichael/code/open-source-projects/openapi-nodegen/node_modules/tslib/tslib.js:107:62)
```

**Comment by dvdsgl** [comment]
Ah, yes, that’s a lot of ceremony to understand! I’ll follow up soon with an example of how to call it.

✌️David

________________________________

**Comment by Acrontum-Carmichael** [comment]
Much appreciated. I am using quicktype in this tool: https://github.com/acrontum/openapi-nodegen/blob/master/src/lib/generate/generateTypeScriptInterfaceText.ts#L22

Currently the tool writes to disc every json schema to be able to give it to quicktype which is then called in a node child spawn process which is very slow with lots of interfaces to generate :)

All I need to be able to do is throw it a json-schema object and get in return the interface string in return as it does in your browser demo :+1:

**Comment by dvdsgl** [comment]
Here you go: https://runkit.com/dvdsgl/5dffa01dedf1a1001cf899c3

**Comment by Acrontum-Carmichael** [comment]
Thank you so much!

**Comment by JipBoesenkool** [comment]
Trying to following you example, any idea why this doesn't work?
It fails on the first option it finds saying Error: Unknown value false for option wstring.

`const options = {
    //typeSourceStyle: EnumOption<boolean>,
    //includeLocation: EnumOption<boolean>,
    //codeFormat: EnumOption<boolean>,
    'wstring': 'false',
    'msbuildPermissive': 'true',
    'justTypes': 'false',
    'namespace': "Model",
    'enumType': "int",
    'typeNamingStyle': "pascal",
    'memberNamingStyle': "camel",
    'enumeratorNamingStyle': "upper-underscore",
    'boost': 'false'
  };

  const lang = new CPlusPlusTargetLanguage("C++", ["cplusplus"], "cpp");
  const { lines } = await quicktype({ lang, inputData, rendererOptions: options });`

Thank you

**Comment by dvdsgl** [comment]
I’m guessing because you’re using the string `’false’` and not the value ‘false’?

**Comment by JipBoesenkool** [comment]
I have send you a message on slack to discuss the issue. But changing it to false gives the same error

**Comment by JipBoesenkool** [comment]
Nevermind, I assumed it where bool values but the interface actually defines string values too indicate true or false.

**Comment by kmturley** [comment]
Here is a quick demo I made of using quicktype programmatically here:
https://github.com/kmturley/quicktype-typescript-input-demo
