### ISSUE TITLE
Updated docker image fails second step: `nom run test` 

### ISSUE THREAD

**Issue by haikusw** [quicktype/quicktype#1490]
Following the directions at the bottom of https://github.com/quicktype/quicktype the first step succeeds but the second step ( `npm run test` ) fails:

> ● Validation Error:
> 
>   Module ts-jest in the transform option was not found.
>          <rootDir> is: /quicktype

I updated to the latest docker ( Docker version 19.03.8, build afacb8b ) and pulled the latest source from https://github.com/quicktype/quicktype master branch and then ran:

`script/dev` as directed but the instructions.  Lots of output with various messages but nothing obviously "FAILED" or "ERROR" and it completed successfully and was launched by Docker.

This is on macOS X 10.15.4.

More detailed log:

> root@aa778246e515:/quicktype# npm run test --verbose
> npm info it worked if it ends with ok
> npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test', '--verbose' ]
> npm info using npm@6.13.4
> npm info using node@v8.17.0
> npm verb run-script [ 'pretest', 'test', 'posttest' ]
> npm info lifecycle quicktype@15.0.0~pretest: quicktype@15.0.0
> npm info lifecycle quicktype@15.0.0~test: quicktype@15.0.0
> 
> > quicktype@15.0.0 test /quicktype
> > jest && script/test
> 
> ● Validation Error:
> 
>   Module ts-jest in the transform option was not found.
>          <rootDir> is: /quicktype
> 
>   Configuration Documentation:
>   https://jestjs.io/docs/configuration.html
> 
> npm verb lifecycle quicktype@15.0.0~test: unsafe-perm in lifecycle true
> npm verb lifecycle quicktype@15.0.0~test: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/quicktype/node_modules/.bin:/app/node_modules/.bin:/root/.sdkman/candidates/kotlin/current/bin:/root/.cargo/bin:/app/swift-4.1.3-RELEASE-ubuntu16.04/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> npm verb lifecycle quicktype@15.0.0~test: CWD: /quicktype
> npm info lifecycle quicktype@15.0.0~test: Failed to exec test script
> npm verb stack Error: quicktype@15.0.0 test: `jest && script/test`
> npm verb stack Exit status 1
> npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> npm verb stack     at emitTwo (events.js:126:13)
> npm verb stack     at EventEmitter.emit (events.js:214:7)
> npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> npm verb stack     at emitTwo (events.js:126:13)
> npm verb stack     at ChildProcess.emit (events.js:214:7)
> npm verb stack     at maybeClose (internal/child_process.js:915:16)
> npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> npm verb pkgid quicktype@15.0.0
> npm verb cwd /quicktype
> npm verb Linux 4.19.76-linuxkit
> npm verb argv "/usr/bin/node" "/usr/bin/npm" "run" "test" "--verbose"
> npm verb node v8.17.0
> npm verb npm  v6.13.4
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! quicktype@15.0.0 test: `jest && script/test`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the quicktype@15.0.0 test script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm verb exit [ 1, true ]
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> npm timing npm Completed in 324ms
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-06-01T03_29_16_824Z-debug.log
> root@aa778246e515:/quicktype# 
>

**Comment by haikusw** [comment]
Huh. Second time it looks to have died here:

> Step 47/56 : RUN curl -sL "https://keybase.io/crystal/pgp_keys.asc" | apt-key add -
>  ---> Running in 6115ac5043ec
> gpg: no valid OpenPGP data found.
> The command '/bin/sh -c curl -sL "https://keybase.io/crystal/pgp_keys.asc" | apt-key add -' returned a non-zero code: 2
> Unable to find image 'quicktype:latest' locally
> docker: Error response from daemon: pull access denied for quicktype, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.

Did a re-run and get other errors.  This all seems pretty flakey.

**Comment by haikusw** [comment]
Tried this again and got that same error. ¯\_(ツ)_/¯ 

Haven't had this kind of trouble with any other docker images.  This one is more complex than most it seems like (so many languages etc).

**Comment by haikusw** [comment]
Curious if anyone can get this docker image to work on macOS 10.15.4 using Docker version 19.03.8, build afacb8b
