### ISSUE TITLE
Primordials is not defined while running npm install

### ISSUE THREAD

**Issue by cbmgit** [quicktype/quicktype#1743]
I am trying to build quicktype in local env and facing npm build issue.

Latest quicktype code:
Node version: 14.17.1
npm version: 6.14.13
OS : Ubuntu 20 (Facing the same issue in windows.)
```

> elm@0.18.0-exp5 install /home/root/git/quicktype/node_modules/elm
> npx binwrap-install

primordials is not defined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.18.0-exp5 install: `npx binwrap-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elm@0.18.0-exp5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by jhult** [comment]
I just bumped into the same issue:

```
node_modules/.pnpm/elm@0.18.0-exp5/node_modules/elm: Running install script, failed in 1.1s
.../elm@0.18.0-exp5/node_modules/elm install$ npx binwrap-install
│ fs.js:47
│ } = primordials;
│     ^
│ ReferenceError: primordials is not defined
│     at fs.js:47:5
│     at req_ (/Users/jonathan/development/quicktype/node_modules/.pnpm/natives@1.1.6/node_modules/natives/index.js:143:24)
│     at Object.req [as require] (/Users/jonathan/development/quicktype/node_modules/.pnpm/natives@1.1.6/node_modules/natives/index.js:55:10)
│     at Object.<anonymous> (/Users/jonathan/development/quicktype/node_modules/.pnpm/graceful-fs@3.0.12/node_modules/graceful-fs/fs.js:1:37)
│     at Module._compile (node:internal/modules/cjs/loader:1109:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
│     at Module.load (node:internal/modules/cjs/loader:989:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:829:14)
│     at Module.require (node:internal/modules/cjs/loader:1013:19)
│     at require (node:internal/modules/cjs/helpers:93:18)
└─ Failed in 1.1s
 ERROR  Command failed with exit code 1.
```

Bumping [Elm](https://www.npmjs.com/package/elm) (in [package.json](https://github.com/quicktype/quicktype/blob/master/package.json)) to the latest version, currently `0.19.1-5`, fixed the issue for me.

I believe merging PR #1653 would resolve this.

**Comment by cbmgit** [comment]
This has resolve the issue. Now I am able to build with npm install.

**Comment by andyjdavis** [comment]
The "ReferenceError: primordials is not defined" error still occurs if you try and `npm install` this repo. I am using npm version 8.1.0 in case that is important.

Bumping elm worked for me too.
