### ISSUE TITLE
Cannot run quicktype after pulling down current master code.

### ISSUE THREAD

**Issue by bzuidgeest** [quicktype/quicktype#2100]
@dvdsgl I just tried to quickly look at #2097, but after checkout the current code from master, i can build the code, but when I try to run it 
bart@IdefixHome:~/repos/quicktype$ script/quicktype
/home/bart/repos/quicktype/dist/quicktype-core/Run.js:147
    _options;
            ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/bart/repos/quicktype/dist/quicktype-core/index.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/bart/repos/quicktype/dist/cli/index.js:33:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Do you know what could cause that?

**Comment by dvdsgl** [comment]
@bzuidgeest are you using the correct `node` version? Works for me.

**Comment by bzuidgeest** [comment]
node -v says
v10.19.0

npm version
{ quicktype: '18.0.0',
  npm: '6.14.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '36.1',
  http_parser: '2.9.3',
  icu: '66.1',
  modules: '64',
  napi: '5',
  nghttp2: '1.40.0',
  node: '10.19.0',
  openssl: '1.1.1d',
  tz: '2022g',
  unicode: '13.0',
  uv: '1.34.2',
  v8: '6.8.275.32-node.55',
  zlib: '1.2.11' }

to be certain I cloned this repo, not my fork (which I synced) . 
I do an npm build and it gives a few warnings like:
Building quicktype-typescript-input
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
But not much else.

This is WSL2 using ubuntu. 

script/quicktype still gives that same error.

I am not at all familiar with typescript and the nodejs/npm eco system. I'm mostly a c# guy, but between stackoverflow and most languages using different syntax yet having the same functionality, I can string a few things together :). Unfortunately this seems quicktype specific.

**Comment by dvdsgl** [comment]
You are not on the right node version. Please see the README.

**Comment by bzuidgeest** [comment]
I'm sorry, I must be missing something, bacause I cannot find mention of a specific node version in de README in the repo.
I assumed the latest from ubuntu would be fine. If not I can adjust.

**Comment by dvdsgl** [comment]
`nvm install` will install the required mode version, which is stored in `.nvmrc`
