### ISSUE TITLE
Error when running from the command line.

### ISSUE THREAD

**Issue by TroyLDay** [quicktype/quicktype#2167]
I'm using/evaluating quicktype for the first time. My goal is to run it from an npm postinstall script to generate typescript interfaces from jsonschema. So I added it to my angular project...

> npm install -save-dev quicktype 

It installs without a problem: package.json:
"quicktype": "^21.0.10",

When I try to run it from the command line:
> npx quicktype

...node_modules\quicktype-core\node_modules\yaml\dist\compose\composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\dev\lunar-locust\node_modules\quicktype-core\node_modules\yaml\dist\index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

I then went back and installed the 20.0.10 version and I get the same error. I'm guessing this may be an environment issue, not sure. This is on a windows machine. I tried the command from a powershell and git bash prompts. Any advice would be greatly appreciated.

**Comment by dvdsgl** [comment]
I think your version of `node` is too old. Try the LTS version or later.

**Comment by TroyLDay** [comment]
Good call dvdsgl, I upped to 14 lts and all is well. Thank you!
