### ISSUE TITLE
Tests are broken in main branch

### ISSUE THREAD

**Issue by dkozma** [quicktype/quicktype#2268]
I believe the merging of #2260 broke tests in the main branch. When I try to run `npm test` locally, I get:
```
❯ npm test

> quicktype@23.0.0 test
> script/test

/Users/user/Projects/Other/quicktype/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
test/fixtures.ts:84:9 - error TS2322: Type 'string | boolean' is not assignable to type 'string | undefined'.
  Type 'boolean' is not assignable to type 'string'.

84         newEnv["QUICKTYPE_" + o.toUpperCase().replace("-", "_")] = additionalRendererOptions[o];
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/user/Projects/Other/quicktype/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/user/Projects/Other/quicktype/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/user/Projects/Other/quicktype/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/user/Projects/Other/quicktype/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/user/Projects/Other/quicktype/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/user/Projects/Other/quicktype/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  diagnosticCodes: [ 2322 ]
}
```

Looking at the checks from the [PR test run](https://github.com/quicktype/quicktype/actions/runs/4804391212) it looks like this introduced a bunch of errors, however the PR was merged to main anyway. Is this something that can be fixed or reverted?

**Comment by dkozma** [comment]
Closing since it looks like this was fixed in #2279.
