### ISSUE TITLE
Don't use shelljs.mkdir -p

### ISSUE THREAD

**Issue by schani** [quicktype/quicktype#644]
It assumes that no other process tries to make the same directory, and if it does, it fatally exits - no catchable exception.  We'll have to implement this our own.

**Comment by schani** [comment]
```
ShellJS: internal error
  | Error: EEXIST: file already exists, mkdir '/quicktype-outputs/elm/test/inputs/schema'
  | at Object.fs.mkdirSync (fs.js:885:18)
  | at mkdirSyncRecursive (/app/node_modules/shelljs/src/mkdir.js:24:8)
  | at mkdirSyncRecursive (/app/node_modules/shelljs/src/mkdir.js:29:3)
  | at /app/node_modules/shelljs/src/mkdir.js:80:9
  | at Array.forEach (<anonymous>)
  | at Object._mkdir (/app/node_modules/shelljs/src/mkdir.js:58:8)
  | at Object.mkdir (/app/node_modules/shelljs/src/common.js:399:25)
  | at JSONSchemaFixture.<anonymous> (/app/test/fixtures.ts:171:15)
  | at step (/app/test/fixtures.ts:42:23)
  | at Object.next (/app/test/fixtures.ts:23:53)
```
