### ISSUE TITLE
It's not work on linux

### ISSUE THREAD

**Issue by yangbuk84g** [quicktype/quicktype#906]
I think It's clipboard issue

Log;
[2018-06-18 13:58:41.375] [renderer1] [error] spawn xclip ENOENT: Error: spawn xclip ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by dvdsgl** [comment]
Which browser?

**Comment by dvdsgl** [comment]
What did you do to get this error? What were the options and input? Was this the CLI?

**Comment by yangbuk84g** [comment]
os: ubuntu 16.04 LTS x64
where: vs code 1.24.1
https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype
install this extenstion.

I'm sorry to give information slowly and my english is bad..

**Comment by schani** [comment]
Thank you.  Could you please try again with the latest extension version (>=11.0.6)?

If it still doesn't work, please add a comment here: https://github.com/quicktype/quicktype-vscode/issues/7

**Comment by yangbuk84g** [comment]
Thanks it works well.
