### ISSUE TITLE
centos 6.9 install error

### ISSUE THREAD

**Issue by harsszegi** [quicktype/quicktype#973]
Hello can't install it on CentOS 6.9
Any idea how to overcome this?
Thanks,

npm ERR! Error: No compatible version found: unicode-properties@'github:quicktype/unicode-properties#dist'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.1.0"]
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-696.23.1.el6.i686
npm ERR! command "node" "/usr/bin/npm" "install" "quicktype"
npm ERR! cwd /home/Tibor.Harsszegi
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6

Also from npm-debug.log:

1005 verbose git remote.origin.url git://github.com/quicktype/typescript-json-schema
1006 verbose git clone git://github.com/github:quicktype/unicode-properties Initialized empty Git repository in /home/Tibor.Harsszegi/.npm/_git-remotes/git-github-com-github-quicktype-unicode-properties-5dc9de5a/
1006 verbose git clone git://github.com/github:quicktype/unicode-properties
1006 verbose git clone git://github.com/github:quicktype/unicode-properties fatal: remote error:
1006 verbose git clone git://github.com/github:quicktype/unicode-properties   github:quicktype/unicode-properties is not a valid repository name
1006 verbose git clone git://github.com/github:quicktype/unicode-properties   Email support@github.com for help

Btw - as being on RHEL6 - I had to do to be
able to even start installing quicktype

npm config set strict-ssl false

**Comment by harsszegi** [comment]
Use stock nodejs 8.x 32 bit + npm on CentOS, download it from nodejs's homepage and do NOT use the variant from the epel repository.
